Init
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #1
Opened 2022-10-25 09:50 UTC by hhertout

2022-10-25 09:54 UTC, lucianpurcaru approved these changes

2022-10-25 09:55 UTC, greegouze approved these changes

2022-10-25 14:59 UTC, lucianpurcaru approved these changes

2022-10-25 15:00 UTC, greegouze approved these changes

2022-10-25 15:08 UTC, lucianpurcaru approved these changes

2022-10-25 15:09 UTC, greegouze approved these changes

2022-10-25 15:34 UTC, sblondeau requested changes

2022-10-25 15:34 UTC, sblondeau commented on src/View/layout.html.twig
> +			<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymou
le fichier JS de bootstrap doit etre avant le block javascript sinon il ne pourra pas surcharger le code

2022-10-25 15:34 UTC, sblondeau commented on src/View/layout.html.twig
> +		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin
baisse sous le title histoire d'avoir les 3 feuilles de style à la suite

2022-10-25 15:34 UTC, sblondeau commented on migration.php
> +
tu n'as pas à toucher à ce fichier

2022-10-25 15:34 UTC, sblondeau commented on public/assets/css/style.css
> +ul {
ça n'a rien à faire dans la PR d'initailisation

2022-10-25 15:34 UTC, sblondeau commented on public/assets/css/style.css
> +    padding: 0;
ça ça doit déjà etre fait par boostrap, pas besoin de spécifier ce bloc avec étoile

2022-10-25 19:19 UTC, lucianpurcaru approved these changes

2022-10-26 06:54 UTC, greegouze approved these changes

2022-10-26 06:57 UTC, greegouze approved these changes

2022-10-26 07:12 UTC, sblondeau approved these changes

2022-10-26 07:12 UTC, merged