S2US8_Admin can Create an actuality
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #110
Opened 2022-11-06 17:07 UTC by hhertout

2022-11-06 18:19 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-06 21:48 UTC, VioletaBD approved these changes

2022-11-08 07:52 UTC, sblondeau requested changes
j'ai 2 US dans ta PR
- index
- add
Commence par la redécouper stp ;-)

2022-11-08 10:08 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-08 12:57 UTC, sblondeau requested changes

2022-11-08 12:57 UTC, sblondeau commented on src/Controller/AdminActualityController.php
> +    public function index()
la méthode index() est de trop là, ce n'est pas ton US

2022-11-08 12:57 UTC, sblondeau commented on src/Controller/AdminController.php
> +    public function index()
idem ici ce fichier ne devrait pas faire partie de la US

2022-11-08 16:23 UTC, lucianpurcaru approved these changes

2022-11-08 16:28 UTC, greegouze submitted a review, later dismissed

2022-11-08 16:32 UTC, sblondeau requested changes

2022-11-08 16:32 UTC, sblondeau commented on public/assets/css/style.css
> +    overflow-x: hidden;
bof bof

2022-11-08 16:32 UTC, sblondeau commented on src/View/Admin/admin-add-actuality.html.twig
> +            <label for="date">Date<sup>*</sup></label>
mettre une étoile c'est pas forcément nécessaire
d'autant plus que tous les champs sont obligatoires

2022-11-08 19:22 UTC, lucianpurcaru approved these changes

2022-11-09 07:53 UTC, sblondeau approved these changes

2022-11-09 07:53 UTC, merged