S2 us42 association
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #130
Opened 2022-11-09 15:31 UTC by VioletaBD

2022-11-09 15:54 UTC, hhertout reviewed
Tu peux supprimer le fichier association.css vu qu'il est vide

2022-11-09 16:07 UTC, hhertout requested changes

2022-11-09 16:07 UTC, hhertout commented on src/View/Association/_associations.html.twig
> +						<h5 class="card-text mt-5">{{ association.categoryName }}</h5>
Le nom de l'association doit être à côté de l'image comme sur la maquette Figma

2022-11-09 16:07 UTC, hhertout commented on src/View/Association/_associations.html.twig
> +							<h3><button type="button" class="btn btn-outline-primary mt-1 mb-3">
bon-outline-primary ? Ce ne serait pas mieux en bg-primary pour être harmonieux par rapport au reste du site ? Je ne me rend pas compte du visuel...

2022-11-10 11:03 UTC, hhertout approved these changes

2022-11-10 11:04 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-10 16:20 UTC, Zakari-B requested changes

2022-11-10 16:20 UTC, Zakari-B commented on database.sql
> +DROP TABLE Association;
A retirer ou alors mettre IF EXISTS.

2022-11-10 16:20 UTC, Zakari-B commented on database.sql
> +DROP TABLE Category;
Idem

2022-11-11 11:11 UTC, lucianpurcaru approved these changes

2022-11-14 08:23 UTC, sblondeau requested changes

2022-11-14 08:23 UTC, sblondeau commented on database.sql
> +    Association (
nom des tables en minuscule

2022-11-14 08:23 UTC, sblondeau commented on database.sql
> +    Category (
nom des tables en minuscule

2022-11-14 08:23 UTC, sblondeau commented on src/Model/AssociationManager.php
> +        $query = "SELECT Association.name as associationName,
nom des tables en minuscule

2022-11-14 08:23 UTC, sblondeau commented on src/View/Association/_associations.html.twig
> +						<img class="association-img-phone bg-primary" src="../assets/images/association_images/telephon.png" alt="Telephone"/>
utilise plutot une icone svg (bootstrap icon par ex)

2022-11-14 08:23 UTC, sblondeau commented on src/View/Association/association.html.twig
> +        {
remplissez la sidebar dès maintenant

2022-11-14 09:04 UTC, hhertout commented on src/View/Association/association.html.twig
> +        {
Ce sera les filtres ici, je comptais les remplirs sur la PR dédiée à ça ?

2022-11-14 09:28 UTC, lucianpurcaru approved these changes

2022-11-14 10:02 UTC, merged