Sp02 us53
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #136
Opened 2022-11-10 09:49 UTC by ByZirTox

2022-11-10 10:01 UTC, sblondeau requested changes
le dossier upload ne doit PAS etre versionné ! 
enlevé les images avec un git rm --cached upload/*
et ajoute un gitignore
et tu as aussi des images uploadstuile et uplodsincendie directe dans public ?!

2022-11-10 11:09 UTC, greegouze approved these changes

2022-11-11 12:05 UTC, greegouze approved these changes

2022-11-11 12:07 UTC, greegouze submitted a review, later dismissed

2022-11-14 08:49 UTC, sblondeau requested changes
tjs des images dans uploads ! as tu mis un .gitignore dans uploads ?

2022-11-14 08:49 UTC, sblondeau commented on src/View/Municipalite/add.html.twig
> +<ul class="alert alert-danger">
pb d'indentation ?

2022-11-14 10:06 UTC, greegouze submitted a review, later dismissed

2022-11-14 10:07 UTC, sblondeau commented
tjs une image dans uploads

2022-11-14 11:40 UTC, sblondeau commented
Tedy ce que je veux c'est que tu ajoutes dans uploads un fichier .gitigore, qui contiendra
```
*
!.gitignore
```
comme ça le dossier est bien versionné (sinon git ne sais pas versionné des dossiers vides) et dans ce nouveau fichier gitinore (qui s'applique uniquement au dossier où il se trouve, tu spécifie que tu ne versionne rien (étoile) SAUF le fichier .gitignore lui meme (via la négation !)

2022-11-15 12:35 UTC, sblondeau approved these changes

2022-11-15 12:35 UTC, merged