S03 us59 add report
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #151
Opened 2022-11-14 22:27 UTC by lucianpurcaru

2022-11-15 16:29 UTC, greegouze submitted a review, later dismissed

2022-11-15 16:33 UTC, hhertout submitted a review, later dismissed

2022-11-16 07:48 UTC, sblondeau requested changes
partie avec les categories à revoir

2022-11-16 07:48 UTC, sblondeau commented on src/View/Admin/admin-report.html.twig
> +<a href="/admin/documents/ajouter" class="btn bg-primary text-secondary mb-4 p-3">Créer une document</a>
Créer un document

2022-11-16 07:48 UTC, sblondeau commented on src/Controller/AdminReportController.php
> +        if (empty($report['title'])) {
verification de la longueur ?

2022-11-16 07:48 UTC, sblondeau commented on src/View/Admin/admin-add-report.html.twig
> +			<select type="report_category" id="report_category" name='category' required>
ça ça doit être construit depuis la BDD (donc tu dois recup un selectAll sur le CategoryManager

2022-11-16 11:35 UTC, hhertout submitted a review, later dismissed

2022-11-16 14:25 UTC, sblondeau requested changes

2022-11-16 14:25 UTC, sblondeau commented on cspell.json
> +{
c'est quoi ce fichier ?

2022-11-16 14:25 UTC, sblondeau commented on src/Controller/AdminReportController.php
> +        if (empty($report['title']) > 255) {
tu as un empty à la place de strlen
et ça doit etre `> $maxLength`
et dans l'erreur "le titre doit faire moins de ". $maxLength . " caractères"
=> c'est mieux pour l'utilisateur

2022-11-16 14:25 UTC, sblondeau commented on src/Controller/AdminReportController.php
> +    public function toCategoryId($categoryName): int
tjs cette méthode qui renvoie des id et qui doit disparaitre

2022-11-16 14:25 UTC, sblondeau commented on src/View/Admin/admin-add-report.html.twig
> +            <option value="{{ category.name }}">{{ category.name }}</option>
value={{ category.id }} et non category.name
du coup en BDD tu dois utilise ta  clé étrangère category_id

2022-11-16 16:25 UTC, hhertout approved these changes

2022-11-16 16:25 UTC, hhertout submitted a review, later dismissed

2022-11-16 16:49 UTC, sblondeau requested changes

2022-11-16 16:49 UTC, sblondeau commented on src/Controller/AdminReportController.php
> +            $errors[] = 'Votre fichier doit être inférieur à ' . self::MAX_FILE_SIZE / 20000000 . 'Mo.';
divisé par 1000000 pas par 2000000

2022-11-16 16:49 UTC, sblondeau commented on src/Controller/AdminReportController.php
> +        if (in_array($report['category'], self::CATEGORY)) {
plus besoin de cette constante, il faut que ton tableau $categories proviennent d'un selectAll() des category en bdd

2022-11-16 20:09 UTC, greegouze submitted a review, later dismissed

2022-11-17 08:23 UTC, greegouze submitted a review, later dismissed

2022-11-17 08:24 UTC, sblondeau approved these changes

2022-11-17 08:29 UTC, greegouze approved these changes

2022-11-17 09:28 UTC, merged