S3US43 Associations Filters
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #157
Opened 2022-11-15 19:13 UTC by hhertout

2022-11-15 19:36 UTC, lucianpurcaru approved these changes

2022-11-16 07:54 UTC, sblondeau requested changes

2022-11-16 07:54 UTC, sblondeau commented on src/View/Association/_association-card.html.twig
> +		<button type="button" class="btn bg-primary w-100 p-2">
pourquoi dans un button ? c'st pas cliquable le num de telephone ?

2022-11-16 07:54 UTC, sblondeau commented on src/View/Association/association.html.twig
> +            'title' : 'Association Culturelles',
tu ne dois jamais te reposer en dur sur l'id car ça peut changer d'une bdd à l'autre
tu as une table categ, tu dois boucler dessus pour construire ton tableau de liens

2022-11-16 07:54 UTC, sblondeau commented on src/View/Association/association.html.twig
> +            'title' : 'Association Culturelles',
ça sera plus court et plus dynamique aussi ;-) si tu ajoutes une categ elle sera automatiquement là

2022-11-16 07:54 UTC, sblondeau commented on src/Model/AssociationManager.php
> +    public function selectByCategory(int $categoryId): array
on pourrait aussi imaginer ne garder que cette méthode, et si $categoryId est null, on fait pas le where

2022-11-16 11:05 UTC, merged