S3 us45 add association
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #162
Opened 2022-11-16 14:22 UTC by VioletaBD

2022-11-16 16:24 UTC, hhertout approved these changes

2022-11-16 22:11 UTC, greegouze approved these changes

2022-11-17 08:17 UTC, hhertout submitted a review, later dismissed

2022-11-17 09:40 UTC, sblondeau requested changes
tu as 2 US en une, tu fais l'affichage ET l'ajout en meme temps !

2022-11-17 09:40 UTC, sblondeau commented on src/View/Admin/admin-add-association.html.twig
> +			<select id="category" name="category" class="form-select" aria-label="Default select">
non ce select doit etre construit avec une requete en database
les options afficheront le nom des category, mais auront en value d'id de la categ
ce qui fait que tu n'as plus besoin de la méthode toCategorie()

2022-11-17 09:40 UTC, sblondeau commented on src/View/Admin/admin-add-association.html.twig
> +			<select id="category" name="category" class="form-select" aria-label="Default select">
tu peux voir avec Lucian il a eu à peut pret le meme problème sur son US

2022-11-18 16:17 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-18 16:42 UTC, sblondeau approved these changes

2022-11-18 18:44 UTC, hhertout approved these changes

2022-11-18 21:12 UTC, lucianpurcaru approved these changes

2022-11-21 07:03 UTC, merged