Fix Page admin municipaliteTeam CRUD EDIT
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #177
Opened 2022-11-18 11:16 UTC by ByZirTox

2022-11-19 11:15 UTC, hhertout approved these changes

2022-11-19 11:22 UTC, lucianpurcaru approved these changes

2022-11-19 17:04 UTC, greegouze approved these changes

2022-11-21 07:05 UTC, sblondeau requested changes

2022-11-21 07:05 UTC, sblondeau commented on src/Controller/AdminMunicipaliteTeamController.php
> +                'municipaliteManager' => $municipaliteMembers,
non regarde tes noms de variable, je pense que c'est 'municipaliteMembers' => $municipaliteMembers !

2022-11-21 07:05 UTC, sblondeau commented on src/Controller/AdminMunicipaliteTeamController.php
> +                'municipaliteManager' => $municipaliteMember,
non regarde tes noms de variable, je pense que c'est 'municipaliteMember' => $municipaliteMember !

2022-11-21 09:46 UTC, hhertout approved these changes

2022-11-21 13:07 UTC, closed without merging