FIX_SESSION mise en place de la session
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #185
Opened 2022-11-20 09:52 UTC by lucianpurcaru

2022-11-20 10:26 UTC, hhertout submitted a review, later dismissed

2022-11-21 09:34 UTC, Zakari-B requested changes

2022-11-21 09:34 UTC, Zakari-B commented on src/Controller/AdminController.php
> +            header('HTTP/1.1 401 Unauthorized acces');
401 ou 404, on ne mélange pas.

2022-11-21 09:41 UTC, hhertout approved these changes

2022-11-21 09:57 UTC, Zakari-B approved these changes

2022-11-21 10:08 UTC, hhertout approved these changes

2022-11-21 11:02 UTC, merged