S4US Show All Communal Team
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #187
Opened 2022-11-20 10:53 UTC by hhertout

2022-11-20 11:07 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-21 08:15 UTC, lucianpurcaru approved these changes

2022-11-21 10:04 UTC, sblondeau requested changes

2022-11-21 10:04 UTC, sblondeau commented on src/View/Admin/admin-communal-team.html.twig
> +					<p class="w-50 p-0 m-0 text-decoration-underline">Role</p>
Rôle

2022-11-21 10:04 UTC, sblondeau commented on src/View/Admin/admin-communal-team.html.twig
> +					<p class="w-25 p-0 m-0">{{ agent.lastname }} {{ agent.firstname }}</p>
si tu mets qu'une seule colonne, passe le nom de majuscule avec le filtre twig peut-etre ? pour bien distinguer nom et prénom

2022-11-21 10:06 UTC, hhertout commented on src/View/Admin/admin-communal-team.html.twig
> +					<p class="w-25 p-0 m-0">{{ agent.lastname }} {{ agent.firstname }}</p>
Ça marche je fais ça, effectivement ce sera plus clair

2022-11-21 10:13 UTC, lucianpurcaru approved these changes

2022-11-21 10:14 UTC, lucianpurcaru approved these changes

2022-11-21 14:26 UTC, merged