S4US ADD Communal Agent
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #189
Opened 2022-11-20 12:59 UTC by hhertout

2022-11-20 15:48 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-21 11:00 UTC, Zakari-B requested changes

2022-11-21 11:00 UTC, Zakari-B commented on src/Controller/AdminMunicipaliteTeamController.php
> +    public const IS_NOT_COMMUNAL = 0;
S'il n'est pas IS_COMMUNAL, il est automatiquement IS_NOT_COMMUNAL, alors pourquoi ne pas utiliser une seule variable ?

2022-11-21 12:20 UTC, hhertout commented on src/Controller/AdminMunicipaliteTeamController.php
> +    public const IS_NOT_COMMUNAL = 0;
GrumPhp ne veut pas de bool... 
Du coup comment tu set le IS_NOT pour lui envoyer 0 ?

2022-11-21 17:20 UTC, ByZirTox approved these changes

2022-11-22 08:15 UTC, lucianpurcaru approved these changes

2022-11-22 08:16 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-22 09:38 UTC, lucianpurcaru approved these changes

2022-11-22 09:41 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-22 09:56 UTC, lucianpurcaru approved these changes

2022-11-22 10:23 UTC, Zakari-B approved these changes

2022-11-22 10:23 UTC, merged