FIX Municipal Home Page Doublons
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #198
Opened 2022-11-21 17:51 UTC by hhertout

2022-11-21 17:54 UTC, hhertout commented on src/Controller/AdminMunicipaliteTeamController.php
> -        if ($municipaliteMembers && $_SERVER["REQUEST_METHOD"] === "POST") {
J'étais obligé d'y touché...

2022-11-21 19:55 UTC, ByZirTox reviewed
Ont voit ca demain il te manque du code dans mon controller

2022-11-21 19:55 UTC, ByZirTox commented on src/Controller/AdminMunicipaliteTeamController.php
> -        if ($municipaliteMembers && $_SERVER["REQUEST_METHOD"] === "POST") {
oui greg aussi j'ai vue ca avec lui aussi tout est réglée normalement

2022-11-22 07:59 UTC, lucianpurcaru approved these changes

2022-11-22 08:10 UTC, sblondeau requested changes

2022-11-22 08:10 UTC, sblondeau commented on src/View/Municipalite/municipalTeam.html.twig
> +						<h5 class="card-text">{{ employee.firstname }}{{employee.lastname}}</h5>
pas de h5 sans h4, il faut etre cohérent sur l'ordre des titre, là a priori ça serait un h3 ?

2022-11-22 10:34 UTC, lucianpurcaru approved these changes

2022-11-22 10:35 UTC, lucianpurcaru approved these changes

2022-11-22 10:51 UTC, sblondeau approved these changes

2022-11-22 10:51 UTC, merged