FIX REWORK_municipalite
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #201
Opened 2022-11-21 18:41 UTC by hhertout

2022-11-21 18:43 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-21 21:46 UTC, sblondeau requested changes

2022-11-21 21:46 UTC, sblondeau commented on src/View/CityMap/city_map.html.twig
> +	    {
pas moyen de mettre le set sideNav dans un include ou ces valeurs par défaut dans le layout éventuellement? car tu le répètes à l'identique sur 6 ou 7 pages là... si tu as un truc à modifier, faut que tu le fasse partout, pas très DRY ;-)

2022-11-22 11:55 UTC, hhertout commented on src/View/CityMap/city_map.html.twig
> +	    {
J'ai essayer de changer avec ça "{% set sideNav = include('Municipalité/_asideNav.html.twig') %}" avec le tableau dans la vue... mais rien ne s'affiche pour le moment

2022-11-22 11:55 UTC, hhertout commented on src/View/CityMap/city_map.html.twig
> +	    {
Je vais voir pour tester d'autres choses...

2022-11-22 14:00 UTC, closed without merging