coordonnées
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #63
Opened 2022-10-27 07:44 UTC by greegouze

Coordonnées mairie

2022-10-27 08:09 UTC, lucianpurcaru submitted a review, later dismissed

2022-10-27 10:51 UTC, hhertout approved these changes

2022-10-27 14:57 UTC, Zakari-B requested changes

2022-10-27 14:57 UTC, Zakari-B commented on public/assets/css/style.css
> +ul {
Toutes les ul sont modifiées par ce changement, on évite. Il faut utiliser une classe bootstrap ou en créer une soi-même, pas changer l'élément ul directement.

2022-10-28 08:55 UTC, lucianpurcaru submitted a review, later dismissed

2022-10-28 15:15 UTC, ByZirTox approved these changes

2022-10-28 15:15 UTC, lucianpurcaru approved these changes

2022-10-31 08:02 UTC, Zakari-B approved these changes

2022-10-31 08:03 UTC, merged