Sp01 us28
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #66
Opened 2022-10-27 10:05 UTC by greegouze

2022-10-27 11:42 UTC, lucianpurcaru approved these changes

2022-10-27 14:09 UTC, hhertout approved these changes

2022-10-27 14:41 UTC, Zakari-B requested changes

2022-10-27 14:41 UTC, Zakari-B commented on src/Controller/ServicesMunicipauxController.php
> +class ServicesMunicipauxController extends AbstractController
Noms de classes et fichiers en anglais.

2022-10-27 14:41 UTC, Zakari-B commented on src/View/Home/servicesMunicipaux.html.twig
> +					<h4><b><img src="./assets/images/telephone-call.png" height="20" alt="tel"/>
Utiliser un svg plutot qu'un png pour les icones, voir site de bootstrap.

2022-10-27 14:41 UTC, Zakari-B commented on public/assets/css/style.css
> +.services-municipaux, h3{
Non, tous les h3 sont modifiés ici.

2022-10-27 14:41 UTC, Zakari-B commented on public/assets/css/style.css
> +        h4{
Non, même chose que pour les h3, tous les h4 sont modifiés ici.

2022-10-28 08:41 UTC, Zakari-B approved these changes

2022-10-28 08:53 UTC, merged