PeriscolaireUS
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #68
Opened 2022-10-27 10:45 UTC by VioletaBD

2022-10-27 10:53 UTC, hhertout approved these changes

2022-10-27 14:10 UTC, Zakari-B requested changes

2022-10-27 14:10 UTC, Zakari-B commented on database.sql
> +-- Active: 1666785953847@@127.0.0.1@3306@saint_ay
Qu'est ce que c'est que cette modification ?

2022-10-27 14:10 UTC, Zakari-B commented on src/View/Services_municipaux/periscolaire.html.twig
> +          <div class="periscolaireText"
div pas fermée.

2022-10-27 14:10 UTC, Zakari-B commented on src/Controller/PeriscolaireController.php
> +class PeriscolaireController extends AbstractController
Nom de la classe (et les fichiers/dossiers) en anglais. A renommer en fonction de la catégorie principale  plutôt que la sous-catégorie (Vie scolaire ? Services municipaux ?)

2022-10-27 19:51 UTC, lucianpurcaru approved these changes

2022-10-28 08:57 UTC, hhertout commented on src/View/Home/municipalService.html.twig
> +            </div>
Mal indenté.

Ctrl + shift + i

2022-10-29 15:43 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-02 09:28 UTC, hhertout approved these changes

2022-11-02 09:47 UTC, merged