Sp01 us14
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #69
Opened 2022-10-27 14:55 UTC by ByZirTox

2022-10-27 19:24 UTC, hhertout commented on public/assets/css/municipalite.css
> +.card {
Tu vas modifier toutes les cards de la page si tu laisses en l'état.

utilise une classe spécifique pour surcharger bootstrap.

.<nomdelasection><nomdelaclasseasurcharger> {}

2022-10-28 07:42 UTC, hhertout requested changes

2022-10-28 07:42 UTC, hhertout commented on database.sql
> +    Organigramme (
Le nom n'est pas en anglais, ça ne passera pas

2022-10-28 08:37 UTC, hhertout requested changes

2022-10-28 08:37 UTC, hhertout commented on src/Model/MunicipaliteManager.php
> +    public function insert(array $item): int
a delete

2022-10-28 08:53 UTC, lucianpurcaru approved these changes

2022-10-28 08:54 UTC, hhertout approved these changes

2022-10-28 17:53 UTC, hhertout approved these changes

2022-10-31 08:09 UTC, Zakari-B requested changes

2022-10-31 08:09 UTC, Zakari-B commented on public/assets/css/municipalite.css
> +    .municipalityTeam .col-lg-3 {
Faisable en bootstrap sans passer par la media query.

2022-10-31 08:09 UTC, Zakari-B commented on src/Model/MunicipaliteManager.php
> +        $query = 'SELECT firstname, lastname, role, image FROM ' . static::TABLE;
Je crois que c'est self::TABLE que tu voulais, plutôt ?

2022-10-31 08:09 UTC, Zakari-B commented on public/assets/css/municipalite.css
> +        width: 300px;
même valeur de width que en dehors de la media query : inutile de le répéter.

2022-10-31 12:59 UTC, ByZirTox commented on public/assets/css/municipalite.css
> +        width: 300px;
Review

2022-10-31 12:59 UTC, ByZirTox commented on public/assets/css/municipalite.css
> +    .municipalityTeam .col-lg-3 {
REview

2022-10-31 12:59 UTC, ByZirTox commented on src/Model/MunicipaliteManager.php
> +        $query = 'SELECT firstname, lastname, role, image FROM ' . static::TABLE;
review

2022-11-01 12:49 UTC, hhertout approved these changes

2022-11-02 08:34 UTC, Zakari-B requested changes

2022-11-02 08:34 UTC, Zakari-B commented on src/View/Municipalite/index.html.twig
> +				{% for personnes in personne %}
A mettre en anglais, et tu as inversé. Tu choisis une personne dans la liste de personnes à chaque tour de boucle, pas le contraire.

2022-11-02 08:34 UTC, Zakari-B commented on src/Controller/MunicipaliteController.php
> +                'personne' => $municipaliteManager->selectAll(),
Liste de plusieurs personnes, à mettre en anglais et au pluriel pour coller avec mon autre commentaire (passage au singulier quand tu boucles sur cette liste).

2022-11-02 09:03 UTC, Zakari-B submitted a review, later dismissed

2022-11-02 09:09 UTC, hhertout approved these changes

2022-11-02 09:15 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-02 12:54 UTC, greegouze submitted a review, later dismissed

2022-11-02 16:38 UTC, sblondeau requested changes
pas d'image de membres dans assets/images car ce ne sont pas des données à versionner

2022-11-02 16:38 UTC, sblondeau commented on src/Controller/MunicipaliteController.php
> +                'employees' => $municipaliteManager->selectAll(),
order by

2022-11-02 16:38 UTC, sblondeau commented on src/Model/MunicipaliteManager.php
> +    public const TABLE = 'MunicipalityTeam';
pas de majuscule

2022-11-02 16:38 UTC, sblondeau commented on src/Model/MunicipaliteManager.php
> +    public function selectAll(string $orderBy = '', string $direction = 'ASC'): array
pas la peine de redefinir selectAll non ?

2022-11-02 16:39 UTC, sblondeau requested changes

2022-11-02 16:39 UTC, sblondeau commented on public/assets/css/municipalite.css
> +@media screen and (max-width: 768px) {
je suis sur que tu peux faire sans cette media query

2022-11-03 10:06 UTC, lucianpurcaru approved these changes

2022-11-03 10:19 UTC, Zakari-B requested changes

2022-11-03 10:19 UTC, Zakari-B commented on src/Model/MunicipaliteManager.php
> +    public function selectAll(string $orderBy = '', string $direction = 'ASC'): array
Non. A retirer, surtout que l'AbstractManager va déjà select toutes les infos (*).

2022-11-03 11:38 UTC, sblondeau requested changes
il ne faut pas d'images uploadable dans assets/images

2022-11-03 11:38 UTC, sblondeau commented on src/Model/MunicipaliteManager.php
> +class MunicipaliteManager extends AbstractManager
MunicipalityTeamManager plutot ?

2022-11-03 16:25 UTC, sblondeau approved these changes

2022-11-03 16:25 UTC, merged