Sp01 us03
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #70
Opened 2022-10-27 19:29 UTC by greegouze

Mot du maire

2022-10-28 07:24 UTC, lucianpurcaru approved these changes

2022-10-28 15:18 UTC, ByZirTox approved these changes

2022-10-29 15:41 UTC, lucianpurcaru approved these changes

2022-11-02 16:19 UTC, hhertout approved these changes

2022-11-02 16:40 UTC, Zakari-B requested changes

2022-11-02 16:40 UTC, Zakari-B commented on src/View/Home/index.html.twig
> +	  <h3>Horaire d'ouverture au public</h3>
Horaires au pluriel. Pratiques également.

2022-11-03 08:19 UTC, Zakari-B approved these changes

2022-11-03 08:21 UTC, lucianpurcaru approved these changes

2022-11-03 08:22 UTC, merged