S1U05_actus-display
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #71
Opened 2022-10-27 19:30 UTC by hhertout

2022-10-27 19:55 UTC, lucianpurcaru submitted a review, later dismissed

2022-10-27 19:57 UTC, VioletaBD submitted a review, later dismissed

2022-10-27 21:38 UTC, sblondeau requested changes

2022-10-27 21:38 UTC, sblondeau commented on database.sql
> +CREATE TABLE actualite (
actuality en anglais

2022-10-27 21:38 UTC, sblondeau commented on public/assets/css/style.css
> +.home-actualite .card img {
home-actuality

2022-10-27 21:38 UTC, sblondeau commented on src/Controller/HomeController.php
> +use App\Model\ActualiteManager;
idem, à renommer partout

2022-10-27 21:38 UTC, sblondeau commented on src/Controller/HomeController.php
> +        return $this->twig->render('Home/index.html.twig', ['actualit' => $homeActu]);
pas d'abbréviations
'actualities' => $homeActualities

2022-10-27 21:38 UTC, sblondeau commented on src/Model/ActualiteManager.php
> +    public function selectHomeActu()
selectActualities() <= ne précise pas "home" dans le manager, tu pourrais avoir besoin de cette meme requete sur une autre page
Tu peux aussi mettre un paramètre $limit=2 à la méthode afin de te laisser la possiblité d'en recupérer davantage

2022-10-28 07:22 UTC, sblondeau requested changes

2022-10-28 07:22 UTC, sblondeau commented on database.sql
> +CREATE TABLE actualities (
non actuality !!! tjs au singulier les noms de table

2022-10-28 07:22 UTC, sblondeau commented on src/Model/ActualityManager.php
> +    public const TABLE = "actualities";
actuality

2022-10-28 07:44 UTC, sblondeau approved these changes

2022-10-28 07:44 UTC, merged