Sp01 us28 fix
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #76
Opened 2022-10-28 11:01 UTC by hhertout

2022-10-28 11:07 UTC, lucianpurcaru approved these changes

2022-10-28 11:15 UTC, lucianpurcaru submitted a review, later dismissed

2022-10-28 11:43 UTC, sblondeau requested changes

2022-10-28 11:43 UTC, sblondeau commented on public/assets/css/style.css
> +    border-bottom: 1px solid #333;
couleur css en variable

2022-10-28 11:43 UTC, sblondeau commented on src/View/Home/municipalService.html.twig
> +        <p class="lead">Le Service d'incendie et de secours est centralisé sur le département.Pour en savoir plus voir le site www.sdis45.com</p>
département. Pour  
=> manque espace

2022-10-28 11:43 UTC, sblondeau commented on src/View/Home/municipalService.html.twig
> +        <p class="lead">Depuis le 1er septembre 2015 le Centre de Première Intervention(CPI) de Saint - Ay a été dissous et ses fonctions regroupées dans le CPI de Chaingy/Saint - Ay basé à Chaingy.<
"Saint-Ay" pas "Saint - Ay" (espaces en trop) 2 fois dans la phrase

2022-11-02 16:12 UTC, greegouze submitted a review, later dismissed

2022-11-02 16:12 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-02 16:44 UTC, sblondeau requested changes

2022-11-02 16:44 UTC, sblondeau commented on public/assets/css/style.css
>          padding-top: 18px;
tu devrais t'en sortir avec un pt-sm-5 ou qq chose comme ça, sans media query

2022-11-03 16:32 UTC, lucianpurcaru approved these changes

2022-11-03 16:35 UTC, hhertout commented on public/assets/css/style.css
>      color: var(--font-color-body);
A supprimer ce sera déjà en global

2022-11-04 08:40 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-04 09:57 UTC, sblondeau requested changes
image trop grosse

2022-11-04 16:11 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-04 16:17 UTC, sblondeau approved these changes

2022-11-04 16:21 UTC, sblondeau submitted a review, later dismissed

2022-11-05 08:50 UTC, lucianpurcaru approved these changes

2022-11-05 12:13 UTC, greegouze approved these changes

2022-11-07 07:55 UTC, sblondeau approved these changes

2022-11-07 07:55 UTC, merged