Sp01 us37
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #77
Opened 2022-10-28 12:12 UTC by ByZirTox

2022-10-28 15:12 UTC, lucianpurcaru approved these changes

2022-10-29 15:25 UTC, hhertout requested changes

2022-10-29 15:25 UTC, hhertout commented on public/assets/css/municipalService.css
> +    .school .d-flex {
Pas de class bootstrap dans le css

2022-10-29 15:25 UTC, hhertout commented on src/Model/MunicipalServiceManager.php
> +    public const TABLE = '';
Pour laisser une const de BDD avec une string vide ?

2022-10-29 15:26 UTC, hhertout requested changes

2022-10-29 15:26 UTC, hhertout commented on public/assets/css/municipalService.css
> +.kindergarten {
C'est pas de l'anglais ça 😂

2022-10-31 13:03 UTC, ByZirTox commented on public/assets/css/municipalService.css
> +.kindergarten {
Ba si man ^^ lucian ma fait le coup vendredi

2022-10-31 13:04 UTC, ByZirTox commented on src/Model/MunicipalServiceManager.php
> +    public const TABLE = '';
Review

2022-11-03 07:52 UTC, sblondeau requested changes

2022-11-03 07:52 UTC, sblondeau commented on public/assets/css/municipalService.css
> +@media screen and (max-width: 768px) {
pas certain que ce soit utile cette media query, encore une fois ;-) on voit ensemble si besoin

2022-11-03 07:52 UTC, sblondeau commented on public/assets/css/municipalService.css
> +    border-bottom: 1px solid black;
couleur (black) => variable CSS

2022-11-03 10:01 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-03 10:32 UTC, Zakari-B requested changes

2022-11-03 10:57 UTC, Zakari-B approved these changes

2022-11-03 10:57 UTC, merged