S2US56 Side image layout
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #80
Opened 2022-10-30 15:28 UTC by hhertout

2022-10-30 15:34 UTC, lucianpurcaru approved these changes

2022-10-30 16:09 UTC, greegouze approved these changes

2022-10-31 08:19 UTC, Zakari-B requested changes

2022-10-31 08:19 UTC, Zakari-B commented on public/assets/css/home.css
> +    width: 100vw;
Tous les width 100% du css qui ne sont pas modifiés par des breakpoints pourraient être remplacés par des classes w-100 dans le html.

2022-11-01 10:33 UTC, closed without merging