S02 us02
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #83
Opened 2022-10-31 07:16 UTC by lucianpurcaru

2022-10-31 18:29 UTC, hhertout commented on src/Controller/LoginController.php
> +        header('Location: /');
La page de redirection si login / mdp est bon sera la page admin et pas la page d'accueil non ?

2022-10-31 18:29 UTC, hhertout commented on src/Controller/LoginController.php
> +    public function logout()
Je ne suis pas sûr que le nom de la fonction soit bien choisit.
Logout(se déconnecter) pour se connecter à l'espace admin ?

2022-10-31 18:29 UTC, hhertout commented on src/routes.php
> +    'logout' => ['LoginController', 'logout'],
Pareil ici. Logout me semble par le nom le plus adapté ? 🤔

2022-11-02 10:37 UTC, hhertout submitted a review, later dismissed

2022-11-02 11:08 UTC, Zakari-B requested changes

2022-11-02 11:08 UTC, Zakari-B commented on src/Model/UserManager.php
> +        $statement = $this->pdo->prepare("SELECT * FROM " . static::TABLE . " WHERE email=:email");
self::, pas static.

2022-11-02 11:08 UTC, Zakari-B commented on src/View/Item/_navbar_login_admin.html.twig
> +			<img src="/assets/images/logo.png" width="30px" height="40px">
Classe personnalisée plutôt que CSS inline.

2022-11-03 08:10 UTC, hhertout approved these changes

2022-11-03 10:38 UTC, Zakari-B approved these changes

2022-11-03 10:38 UTC, Zakari-B commented on public/assets/css/style.css
> +    border-bottom: 1px solid #333;
Je laisse passer ça sur cette PR mais je veux que ce soit une variable sur la US29.

2022-11-03 10:38 UTC, merged