S2US23-Horaire-reception-Maire
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #89
Opened 2022-11-01 19:18 UTC by hhertout

2022-11-01 20:13 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-02 08:36 UTC, Zakari-B requested changes

2022-11-02 08:36 UTC, Zakari-B commented on src/View/Home/_mayorReception.html.twig
> +    <p>M. le Maire reçoit sur rendez-vous le lundi après midi <p>
Horaires au pluriel pour le h3, et après-midi prend un tiret.

2022-11-02 08:59 UTC, lucianpurcaru approved these changes

2022-11-02 09:07 UTC, Zakari-B approved these changes

2022-11-02 09:07 UTC, merged