FIX z-index liens non cliquable
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #93
Opened 2022-11-02 11:12 UTC by hhertout

2022-11-02 11:38 UTC, lucianpurcaru approved these changes

2022-11-02 13:16 UTC, Zakari-B requested changes

2022-11-02 13:16 UTC, Zakari-B commented on public/assets/css/style.css
> +    border-bottom:  1px solid #333;
La remarque avait déjà été faite, il me semble, de mettre la couleur en variable. C'est peut être passé entre les mailles du filet la première fois, mais il va falloir le changer !

2022-11-02 15:32 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-02 15:54 UTC, hhertout commented on public/assets/css/style.css
> +    border-bottom:  1px solid #333;
C'est sur une PR qui n'est pas encore passée.

2022-11-02 16:48 UTC, Zakari-B commented on public/assets/css/style.css
> +    border-bottom:  1px solid #333;
Pas mon problème ça

2022-11-02 16:53 UTC, sblondeau requested changes

2022-11-02 16:53 UTC, sblondeau commented on public/assets/css/navbar.css
> +    z-index: 10800;
t'es sûr, j'aurais mis 14258 plutot...
jamais de nombre comme ça, sinon tu finis à 1 milliard
l'idéal est de passer par des variable css que tu appelles en fonction de leur rôle sur la page
--index-modal, --index-below, --index-top, etc avec des valeurs 0, 1, 5, 10 par ex

2022-11-02 20:15 UTC, hhertout commented on public/assets/css/navbar.css
> +    z-index: 10800;
J'ai pas trouver comment faire mieux. 😟
Je m'explique: 
La sidebar est en position fixe et doit passer en dessous de la navBar, fixe elle aussi.  
Bootstrap applique par défaut un z-index de 1030 à la sideBar (vérifiée avec l'inspecteur, d'après la doc le max est 1090). 

J'ai donc essayer de modifier le z-index de la sidebar sans jamais réussir a avoir un résultat convenable. 
Si je surcouche la SideBar en mettant un z-index de 1, la Sidebar passe au dessus de la navBar, et en z-index -1 les liens de la sideBar sont non cliquables pour certains... 

J'ai donc pensé que modifier celui de la navBar était le meilleur choix, malgré le z-index stratosphérique qu'il faille mettre pour contourner celui de bootstrap... et là ça marche parfaitement!
C'est soit ça soit je modifie le z-index de certains composant, en prenant le risque de le problème revienne... 

Si tu as une autre idée je suis preneur.  

(J'ai quand même mis un 0 de trop par contre... je corrige déjà ça)

2022-11-03 09:36 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-03 11:15 UTC, lucianpurcaru submitted a review, later dismissed

2022-11-03 11:38 UTC, sblondeau approved these changes

2022-11-03 11:39 UTC, merged