S02 us29
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #94
Opened 2022-11-02 12:44 UTC by lucianpurcaru

2022-11-02 15:35 UTC, hhertout approved these changes

2022-11-02 16:48 UTC, sblondeau requested changes

2022-11-02 16:48 UTC, sblondeau commented on public/assets/css/style.css
> +        .fireman {
on peut faire sans media query ( voir meme remarque sur autre PR)

2022-11-02 16:48 UTC, sblondeau commented on src/View/Urbanism/urbanism.html.twig
> +'link' : '#step_1'
met plutot des id comprehensible plutot que step1, step2...

2022-11-03 08:10 UTC, hhertout approved these changes

2022-11-03 08:14 UTC, sblondeau requested changes

2022-11-03 08:14 UTC, sblondeau commented on src/View/Urbanism/urbanism.html.twig
> +'link' : '#step_1'
non modifié

2022-11-03 09:31 UTC, hhertout approved these changes

2022-11-03 10:52 UTC, Zakari-B requested changes

2022-11-04 14:55 UTC, Zakari-B approved these changes

2022-11-04 14:55 UTC, merged