S2 us12 city heritage
WildCodeSchool/2022-09-php-orleans-project-saintay pull request #97
Opened 2022-11-03 09:19 UTC by VioletaBD

2022-11-03 09:49 UTC, lucianpurcaru approved these changes

2022-11-03 11:28 UTC, hhertout approved these changes

2022-11-03 11:40 UTC, sblondeau requested changes
il y a 2 version de l'image du vitrail, n'en garder qu'une

2022-11-04 14:36 UTC, lucianpurcaru approved these changes

2022-11-05 08:22 UTC, hhertout approved these changes

2022-11-07 07:56 UTC, sblondeau requested changes
encore une image trop grosse (monument aux morts) et renomme le fichier pour qu'il n'y ait pas d'espace dans le nom car ça peut poser des problèmes

2022-11-08 12:53 UTC, closed without merging